//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaYa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Espacios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Espacios()
        {
            this.EspaciosDetalles = new HashSet<EspaciosDetalles>();
            this.ReservasFechasDisponibles = new HashSet<ReservasFechasDisponibles>();
        }
    
        public int EspacioID { get; set; }
        public string Nombre { get; set; }
        public int CategoriaID { get; set; }
        public int Capacidad { get; set; }
        public string Direccion { get; set; }
        public string UbicacionEnlace { get; set; }
        public bool Estacionamiento { get; set; }
        public bool Sanitarios { get; set; }
        public bool AccesoSillaRuedas { get; set; }
        public string ImagenPrev { get; set; }
        public bool Disponible { get; set; }
    
        public virtual Categorias Categorias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EspaciosDetalles> EspaciosDetalles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReservasFechasDisponibles> ReservasFechasDisponibles { get; set; }
    }
}
