//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaYa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservas
    {
        public int ReservaID { get; set; }
        public decimal MontoTotal { get; set; }
        public int UsuarioID { get; set; }
        public Nullable<int> FechaOcupadaID { get; set; }
        public Nullable<int> ReservaFechaID { get; set; }
    
        public virtual FechasOcupadas FechasOcupadas { get; set; }
        public virtual ReservasFechasDisponibles ReservasFechasDisponibles { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
