//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservaYa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservasFechasDisponibles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ReservasFechasDisponibles()
        {
            this.Reservas = new HashSet<Reservas>();
        }
    
        public int ReservaFechaID { get; set; }
        public int EspacioID { get; set; }
        public int FechaDisponibleID { get; set; }
    
        public virtual Espacios Espacios { get; set; }
        public virtual FechasDisponibles FechasDisponibles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservas> Reservas { get; set; }
    }
}
